Description: Downloads the latest version of Logitech Camera Settings.
Identifier: com.github.neilmartin83-recipes.download.Logitech Camera Settings
MinimumVersion: 0.3.1

Input:
  NAME: Logitech Control Center

Process:
- Processor: URLTextSearcher
  Arguments:
    re_pattern: https:\/\/download01\.logi\.com\/web\/ftp\/pub\/techsupport\/cameras\/Webcams\/LogiCameraSettings_\S*\.pkg
    url: https://support.logi.com/api/v2/help_center/en-us/articles.json?label_names=webcontent=productdownload,websoftware=9bf6fc93-8e0b-11e9-a62b-cb4c7fb3c2e2

- Processor: URLDownloader
  Arguments:
    url: '%match%'

- Processor: EndOfCheckPhase

- Processor: CodeSignatureVerifier
  Arguments:
    expected_authority_names:
    - 'Developer ID Installer: Logitech Inc. (QED4VVPZWA)'
    - Developer ID Certification Authority
    - Apple Root CA
    input_path: '%pathname%'
